#!/usr/bin/python
#LED VALUE
# 0 - off
# 1 - green
# 2 - orange
# 3 - red
LED_OFF = 0
LED_GREEN = 1
LED_ORGANGE = 2
LED_RED = 3

BASE_VEL_MAX_UP = 0.5
BASE_VEL_MAX_DOWN = -0.3
BASE_VEL_ANGULAR_Z = 0.8

#------------command
CMD_MOVE ="MOVE"
CMD_AUTO_CHARGE ="AUTO_CHARGE"
CMD_REMOVE_AUTO_CHARGE_MODE = "REMOVE_AUTO_CHARGE"
CMD_RESTART_BASE ="RESTART"
CMD_RESET_BASE ="RESET"
